**1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`**

**2. Find the shape, rank and size of the tensors you created in 1.**

**3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`**

**4. Multiply the two tensors you created in 3 using matrix multiplication**

**5. Multiply the two tensors you created in 3 using the dot product**

**6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`**

**7. Find the min and max values of the tensor you created in 6**

**8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]**

**9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value**

**10. One-hot encode the tensor you created in 9**

## **1.** Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()` and **2** Find the shape, rank and size of the tensors you created in 1.

In [26]:
# Import TensorFlow
import tensorflow as tf
import numpy as np
# print(tf.__version__)

# Scalar
rank_0_tensor = tf.constant(7)
# Vector
rank_1_tensor = tf.constant([2., 4., 6., .8])
# Matrix
rank_2_tensor = tf.constant([[1., 2., 3.],
                            [4., 5., 6.]])
# Tensor
rank_3_tensor = tf.constant([
                             [[0, 1, 2, 3, 4],
                              [5, 6, 7, 8, 9]],
                            [[10, 11, 12, 13, 14],
                              [15, 16, 17, 18, 19]],
                            [[20, 21, 22, 23, 24],
                              [25, 26, 27, 28, 29]],])

print(f"Shapes --- \n rank_0: {rank_0_tensor.shape}\n rank_1: {rank_1_tensor.shape} \n rank_2: {rank_2_tensor.shape} \n rank_3: {rank_3_tensor.shape}")
print(f"Ranks --- \n Scalar: {tf.rank(rank_0_tensor)}\n Vector: {tf.rank(rank_1_tensor)}\n Matrix: {tf.rank(rank_2_tensor)}\n Tensor: {tf.rank(rank_3_tensor)}")
print(f"Sizes --- \n Scalar: {tf.size(rank_0_tensor)}\n Vector: {tf.size(rank_1_tensor)}\n Matrix: {tf.size(rank_2_tensor)}\n Tensor: {tf.size(rank_3_tensor)}")

Shapes --- 
 rank_0: ()
 rank_1: (4,) 
 rank_2: (2, 3) 
 rank_3: (3, 2, 5)
Ranks --- 
 Scalar: 0
 Vector: 1
 Matrix: 2
 Tensor: 3
Sizes --- 
 Scalar: 1
 Vector: 4
 Matrix: 6
 Tensor: 30


## 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`

In [27]:
random_tensor_1 = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1, seed=42))
random_tensor_2 = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1, seed=43))

random_tensor_1, random_tensor_2, random_tensor_1.shape, random_tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.38871264, 0.9390174 , 0.02779686, ..., 0.77485263, 0.08884048,
         0.36768448],
        [0.05382323, 0.36030817, 0.7621852 , ..., 0.30792463, 0.04872847,
         0.30779958],
        [0.24700892, 0.35864186, 0.25744927, ..., 0.8492167 , 0.49105895,
         0.7440883 ],
        [0.22604144, 0.6567452 , 0.9920782 , ..., 0.523309  , 0.2861662 ,
         0.6322497 ],
        [0.93087447, 0.05708921, 0.4755956 , ..., 0.18605065, 0.5702529 ,
         0.46629596]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.575158  , 0.73340034, 0.95740366, ..., 0.59255695, 0.42909563,
         0.21273208],
        [0.12298286, 0.40930772, 0.12741661, ..., 0.31859314, 0.30204487,
         0.7430321 ],
        [0.5432873 , 0.61172366, 0.10576439, ..., 0.06886029, 0.7486274 ,
         0.89916563],
        [0.17365205, 0.9944627 , 0.03198862, ..., 0.9898411 , 0.8810153 ,
         0.11907721],
        [0.93147

## 4. Multiply the two tensors you created in 3 using matrix multiplication

## 5. Multiply the two tensors you created in 3 using the dot product

In [28]:
# Matrix multiplication
tf.matmul(random_tensor_1, tf.transpose(random_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.56749 , 74.979866, 76.17285 , 76.47557 , 75.87292 ],
       [75.90647 , 73.80325 , 73.904526, 75.4225  , 74.35489 ],
       [73.91824 , 73.713356, 75.47664 , 75.080956, 76.24836 ],
       [77.704544, 77.25104 , 79.71524 , 76.092064, 80.04033 ],
       [73.31193 , 76.96314 , 78.67156 , 75.29905 , 75.62494 ]],
      dtype=float32)>

In [29]:
tf.tensordot(tf.transpose(random_tensor_1), random_tensor_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2707218 , 0.7614333 , 1.2009951 , ..., 1.2891505 , 0.72623515,
        1.0777293 ],
       [0.94646263, 1.7134609 , 1.0522332 , ..., 1.3951014 , 1.3686078 ,
        0.9114611 ],
       [0.8648718 , 1.516498  , 0.58561146, ..., 1.6682233 , 1.3902075 ,
        1.282583  ],
       ...,
       [1.2090751 , 1.7498858 , 1.0452583 , ..., 1.293793  , 1.5540857 ,
        1.3606457 ],
       [0.90474313, 0.71812075, 0.63546765, ..., 0.8758804 , 0.7700528 ,
        0.96323675],
       [1.1977167 , 1.5188572 , 0.8852049 , ..., 1.3941977 , 1.4445142 ,
        1.4049331 ]], dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`

## 7. Find the min and max values of the tensor you created in 6

In [30]:
random_tensor_3 = tf.constant(tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1))
random_tensor_3.shape

TensorShape([224, 224, 3])

In [31]:
tf.reduce_min(random_tensor_3).numpy()

3.9339066e-06

In [32]:
tf.reduce_max(random_tensor_3).numpy()

0.9999974

## 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [34]:
random_tensor_4 = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]))
random_tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.42375505, 0.8496175 , 0.40137362],
         [0.27424335, 0.320076  , 0.51495767],
         [0.3240248 , 0.7022381 , 0.461156  ],
         ...,
         [0.75344896, 0.33403838, 0.56422126],
         [0.86030257, 0.06949377, 0.07233977],
         [0.28664875, 0.08720851, 0.881595  ]],

        [[0.8537482 , 0.10569978, 0.77342   ],
         [0.45593345, 0.33224928, 0.1751455 ],
         [0.24887621, 0.4963783 , 0.42069662],
         ...,
         [0.5981107 , 0.79556143, 0.06778312],
         [0.61396646, 0.25105762, 0.618055  ],
         [0.40957665, 0.9716922 , 0.6394652 ]],

        [[0.5211072 , 0.79136086, 0.7569157 ],
         [0.95273757, 0.2005322 , 0.8722459 ],
         [0.7437812 , 0.4307859 , 0.7662208 ],
         ...,
         [0.20415282, 0.2235769 , 0.57906413],
         [0.16295326, 0.200634  , 0.5826837 ],
         [0.6895194 , 0.11014414, 0.26529598]],

        ...,

        [[0.5965642 , 0.8792466 , 

In [36]:
squeezed_tensor = tf.squeeze(random_tensor_4, axis=0)
squeezed_tensor.shape

TensorShape([224, 224, 3])

## 9.  Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [39]:
my_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_tensor.shape

TensorShape([10])

In [42]:
my_tensor[tf.argmax(my_tensor)].numpy()

10

## 10. One-hot encode the tensor you created in 9.

In [44]:
tf.one_hot(my_tensor, depth=10, on_value='hi my name is', off_value='slim shady')

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'slim shady', b'hi my name is', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady'],
       [b'slim shady', b'slim shady', b'hi my name is', b'slim shady',
        b'slim shady', b'slim shady', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady'],
       [b'slim shady', b'slim shady', b'slim shady', b'hi my name is',
        b'slim shady', b'slim shady', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady'],
       [b'slim shady', b'slim shady', b'slim shady', b'slim shady',
        b'hi my name is', b'slim shady', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady'],
       [b'slim shady', b'slim shady', b'slim shady', b'slim shady',
        b'slim shady', b'hi my name is', b'slim shady', b'slim shady',
        b'slim shady', b'slim shady'],
       [b'slim shady', b'slim shady', b'slim shady', b'slim s